/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_ezpzarchive_free: (a: number, b: number) => void;
export const create: (a: any, b: any, c: number) => [number, number, number, number];
export const ezpzarchive_clearCache: (a: number) => void;
export const ezpzarchive_digest: (a: number) => [number, number];
export const ezpzarchive_entriesJson: (a: number) => [number, number, number, number];
export const ezpzarchive_infoJson: (a: number) => [number, number];
export const ezpzarchive_isEncrypted: (a: number) => number;
export const ezpzarchive_isSigned: (a: number) => number;
export const ezpzarchive_needsPassword: (a: number) => number;
export const ezpzarchive_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const ezpzarchive_read: (a: number, b: number, c: number) => [number, number, number, number];
export const ezpzarchive_signerKey: (a: number) => [number, number];
export const ezpzarchive_verifyJson: (a: number) => [number, number];
export const version: () => [number, number];
export const rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_free: (a: number) => void;
export const rust_zstd_wasm_shim_malloc: (a: number) => number;
export const rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
